// Assembles the deployable copy of Growth Command into .command-build/.
//
// Pages resolves `functions/` relative to the working directory, so the two
// projects in this repo cannot share one root: the marketing site deploys from
// here (and picks up ./functions), and this one deploys with --cwd pointed at
// the staging directory below.
//
// Nothing is copied that is not needed to render the board. dashboard/lib,
// dashboard/server.mjs and the brief stay on the laptop.

import { readFile, writeFile, mkdir, rm, cp } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

// The board payload is built HERE, on the laptop, using the dashboard's own
// library code, and frozen into a module the Worker just hands back. Two
// reasons that beats reimplementing the endpoint on Cloudflare:
//
//   1. Shape parity. The front end is being actively worked on and its
//      expectations move; running the same functions the laptop server runs
//      means the payload cannot drift from what the page reads.
//   2. No credentials on the edge. Nothing about the hosted copy can reach
//      Airtable or Anthropic, because it never holds a key.
//
// The cost is that the hosted board is a snapshot as of the last deploy. It is
// a viewer; the laptop stays the system of record.
import { normalize, shape, STAGES } from '../dashboard/lib/prospects.mjs';
import { buildToday } from '../dashboard/lib/queue.mjs';
import { CHANNELS, SEQUENCES } from '../dashboard/lib/sequences.mjs';
import { getSettings } from '../dashboard/lib/settings.mjs';
import { localDate } from '../dashboard/lib/localdate.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const OUT = join(ROOT, '.command-build');
const SITE = join(OUT, 'site');

const readJson = async (path, what) => {
  try {
    return JSON.parse(await readFile(path, 'utf8'));
  } catch (e) {
    throw new Error(`Could not read ${what} (${path}): ${e.message}`);
  }
};

await rm(OUT, { recursive: true, force: true });
await mkdir(SITE, { recursive: true });

// --- the board payload, frozen into a module -------------------------------
const sample = await readJson(join(ROOT, 'dashboard/data/sample-data.json'), 'the sample board');
const audit = await readJson(join(ROOT, 'dashboard/data/site-audit.json'), 'the site audit');

const today = localDate();
const settings = await getSettings();

// Sample records only. Real prospects live in Airtable and are deliberately
// NOT published: putting a prospect list on a public address is a decision for
// Danish to make, not a side effect of wanting the board on his phone.
const rows = (sample.prospects || []).map((p) => shape(normalize(p), { touches: [], today }));

const board = {
  builtAt: new Date().toISOString(),
  // Everything the edge cannot do, reported honestly rather than faked.
  backend: {
    store: 'snapshot',
    drafter: false,
    research: false,
    model: '',
    tables: {},
    spend: { drafts: 0, cost: 0 },
  },
  caps: settings.caps,
  stages: STAGES,
  channels: CHANNELS,
  sequences: SEQUENCES,
  today: buildToday({ prospects: rows, touches: [], caps: settings.caps, today }),
  prospects: rows,
  recentTouches: [],
  clients: sample.clients || [],
  campaigns: sample.campaigns || [],
  templates: sample.templates || [],
  activity: sample.activity || [],
  siteAudit: audit.siteAudit || [],
};

await cp(join(HERE, 'functions'), join(OUT, 'functions'), { recursive: true });
await cp(join(HERE, 'shared'), join(OUT, 'shared'), { recursive: true });

await writeFile(
  join(OUT, 'shared/board.js'),
  `// Generated by command/build.mjs — do not edit.\n` +
    `// Source: dashboard/data/sample-data.json + dashboard/data/site-audit.json\n` +
    `export const BOARD = ${JSON.stringify(board, null, 2)};\n`,
);

// --- the front end, copied verbatim ----------------------------------------
// Byte-for-byte the same files the laptop server hands out. The URL shape here
// matches that server exactly (/ , /login, /api/*), which is the reason this
// is its own Pages project rather than a path on the marketing site: mounting
// it under /command would have meant rewriting every absolute path in a file
// that is being actively worked on.
for (const file of ['index.html', 'login.html']) {
  await cp(join(ROOT, 'dashboard/public', file), join(SITE, file));
}

// The one edit made to the copy: the laptop's login page says "Local network
// only", which stops being true the moment this is on an address anyone can
// reach. Patched here rather than in dashboard/public/ so the file the laptop
// server serves keeps telling the truth about itself.
const loginPath = join(SITE, 'login.html');
const login = await readFile(loginPath, 'utf8');
const FROM = '<p class="foot">Local network only</p>';
const TO = '<p class="foot">Internal &middot; hosted</p>';
if (!login.includes(FROM)) {
  throw new Error(`login.html no longer contains the footer this script rewrites (${FROM}). Update command/build.mjs.`);
}
await writeFile(loginPath, login.replace(FROM, TO));

await writeFile(
  join(SITE, '_headers'),
  `/*\n` +
    `  X-Robots-Tag: noindex, nofollow\n` +
    `  X-Frame-Options: DENY\n` +
    `  Referrer-Policy: no-referrer\n` +
    `  Cache-Control: no-store\n`,
);

const counts = Object.entries(board)
  .filter(([, v]) => Array.isArray(v))
  .map(([k, v]) => `${v.length} ${k}`)
  .join(', ');
console.error(`  board: ${counts}`);
process.stdout.write(OUT + '\n');
